### ISSUE TITLE
Get NSF grant number for acknowledgments

### ISSUE THREAD

**Issue by MKLau** [HFpostdoc/poster2015#1]

**Comment by amellison17** [comment]
NSF grant # DEB 11-44056

A.

**Comment by MKLau** [comment]
I knew github was good for something!


Sent using CloudMagic<https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.3.45&pv=4.1.2>

On Wed, Jul 29, 2015 at 8:40 PM, Aaron Ellison <notifications@github.com<mailto:notifications@github.com>> wrote:

NSF grant # DEB 11-44056

A.

**Comment by amellison17** [comment]
Dog knows what, though.

A.

**Comment by bbaiser** [comment]
Hey Guys,
As much as I am interested in the inner workings of your poster
presentation, is there a way to get me off this email thread?

Also, what is going on with our network metrics review?

I hope all is well and that summer is much less humid for you than it is
for me.

See you at ESA.

Cheers,
Ben
